const testTalkArr = [
  {
    startTime: '09:00AM',
    name: 'Writing Fast Tests Against Enterprise Rails',
    duration: 60,
    track: 1,
    session: 'morning',
    rawName: 'Writing Fast Tests Against Enterprise Rails 60min',
  },
  {
    startTime: '10:00AM',
    name: 'Overdoing it in Python',
    duration: 45,
    track: 1,
    session: 'morning',
    rawName: 'Overdoing it in Python 45min',
  },
  {
    startTime: '10:45AM',
    name: 'Lua for the Masses',
    duration: 30,
    track: 1,
    session: 'morning',
    rawName: 'Lua for the Masses 30min',
  },
  {
    startTime: '11:15AM',
    name: 'Ruby Errors from Mismatched Gem Versions',
    duration: 45,
    track: 1,
    session: 'morning',
    rawName: 'Ruby Errors from Mismatched Gem Versions 45min',
  },
  {
    startTime: '01:00PM',
    name: 'Common Ruby Errors',
    duration: 45,
    track: 1,
    session: 'afternoon',
    rawName: 'Common Ruby Errors 45min',
  },
  {
    startTime: '01:45PM',
    name: 'Rails for Python Developers',
    duration: 5,
    track: 1,
    session: 'afternoon',
    rawName: 'Rails for Python Developers lightning',
  },
  {
    startTime: '01:50PM',
    name: 'Communicating Over Distance',
    duration: 60,
    track: 1,
    session: 'afternoon',
    rawName: 'Communicating Over Distance 60min',
  },
  {
    startTime: '02:50PM',
    name: 'Accounting-Driven Development',
    duration: 45,
    track: 1,
    session: 'afternoon',
    rawName: 'Accounting-Driven Development 45min',
  },
  {
    startTime: '03:35PM',
    name: 'Woah',
    duration: 30,
    track: 1,
    session: 'afternoon',
    rawName: 'Woah 30min',
  },
  {
    startTime: '04:05PM',
    name: 'Sit Down and Write',
    duration: 30,
    track: 1,
    session: 'afternoon',
    rawName: 'Sit Down and Write 30min',
  },
  {
    startTime: '09:00AM',
    name: 'Pair Programming vs Noise',
    duration: 45,
    track: 2,
    session: 'morning',
    rawName: 'Pair Programming vs Noise 45min',
  },
  {
    startTime: '09:45AM',
    name: 'Rails Magic',
    duration: 60,
    track: 2,
    session: 'morning',
    rawName: 'Rails Magic 60min',
  },
  {
    startTime: '10:45AM',
    name: 'Ruby on Rails: Why We Should Move On',
    duration: 60,
    track: 2,
    session: 'morning',
    rawName: 'Ruby on Rails: Why We Should Move On 60min',
  },
  {
    startTime: '01:00PM',
    name: 'Clojure Ate Scala (on my project)',
    duration: 45,
    track: 2,
    session: 'afternoon',
    rawName: 'Clojure Ate Scala (on my project) 45min',
  },
  {
    startTime: '01:45PM',
    name: 'Programming in the Boondocks of Seattle',
    duration: 30,
    track: 2,
    session: 'afternoon',
    rawName: 'Programming in the Boondocks of Seattle 30min',
  },
  {
    startTime: '02:15PM',
    name: 'Ruby vs. Clojure f or Back-End Development',
    duration: 30,
    track: 2,
    session: 'afternoon',
    rawName: 'Ruby vs. Clojure f or Back-End Development 30min',
  },
  {
    startTime: '02:45PM',
    name: 'Ruby on Rails Legacy App Maintenance',
    duration: 60,
    track: 2,
    session: 'afternoon',
    rawName: 'Ruby on Rails Legacy App Maintenance 60min',
  },
  {
    startTime: '03:45PM',
    name: 'A World Without HackerNews',
    duration: 30,
    track: 2,
    session: 'afternoon',
    rawName: 'A World Without HackerNews 30min',
  },
  {
    startTime: '04:15PM',
    name: 'User Interface CSS in Rails Apps',
    duration: 30,
    track: 2,
    session: 'afternoon',
    rawName: 'User Interface CSS in Rails Apps 30min',
  },
];

module.exports = { testTalkArr };
