const MIN_TRACK_DURATION = 360;
const MAX_TRACK_DURATION = 420;

const MIN_TALK_DURATION = 5;
const MAX_TALK_DURATION = 60;

const BASE_TALK_START_TIME = '09:00AM';

module.exports = {
  MIN_TRACK_DURATION,
  MAX_TRACK_DURATION,
  MIN_TALK_DURATION,
  MAX_TALK_DURATION,
  BASE_TALK_START_TIME,
};
